model_family: llama2-7b
model_path: null
LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

lr: 1e-5
split: forget10
data_path: /p/compressionleakage/llm_privacy/tofu/dataset
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 10
forget_loss: grad_diff
save_dir: ${model_path}/../4GPU_${forget_loss}_${lr}_${split}_new
overwrite_dir: true
weight_decay: 0.01

eval:
  retain_result: /p/compressionleakage/llm_privacy/tofu/data/retain90_llama_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  model_path: ${..model_path}
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  data_path: [/p/compressionleakage/llm_privacy/tofu/dataset, /p/compressionleakage/llm_privacy/tofu/dataset, /p/compressionleakage/llm_privacy/tofu/dataset, /p/compressionleakage/llm_privacy/tofu/dataset]
  split: ${..split}_perturbed
  split_list:
    - retain_perturbed
    - real_authors_perturbed
    - world_facts_perturbed
    - ${split}

  eval_task: [eval_log, eval_real_author_wo_options, eval_real_world_wo_options, eval_log_forget]
  question_key: [question, question, question, question]
  answer_key: [answer, answer, answer, answer]
  base_answer_key: [paraphrased_answer, answer, answer, paraphrased_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer, perturbed_answer, perturbed_answer]

  generation:
    max_length: 200
    max_new_tokens: null

  save_generated_text: true

  ds_size: 300

  overwrite: true
  use_pretrained: false

  batch_size: 30