model_family: gpt-neo
model_path: null
LoRA:
  r: 0
  alpha: 32
  dropout: 0.05

lr: 1e-5
split: forget
# data_path: /p/compressionleakage/llm_privacy/tofu/dataset
data_path: cache_100_200_1000_512/train
batch_size: 4
gradient_accumulation_steps: 4
num_epochs: 10
forget_loss: grad_diff
save_dir: paper_models/4GPU_${forget_loss}_${lr}_${split}_new_2
overwrite_dir: true
weight_decay: 0.01

eval:
  retain_result: /sfs/weka/scratch/deu9yh/llm_privacy/tofu/data/retain90_llama_wd0.01/eval_results/ds_size300/eval_log_aggregated.json
  model_path: ${..model_path}
  model_family: ${..model_family}
  save_dir: ${..save_dir}
  forgot_dir: ${..data_path}
  data_path: [/sfs/weka/scratch/deu9yh/llm_privacy/cache_100_200_1000_512/train, /sfs/weka/scratch/deu9yh/llm_privacy/cache_100_200_1000_512/train, /sfs/weka/scratch/deu9yh/llm_privacy/cache_100_200_1000_512/train, /sfs/weka/scratch/deu9yh/llm_privacy/cache_100_200_1000_512/train]
  split: ${..split}
  split_list:
    - retain
    - ${split}

  eval_task: [eval_retain, eval_log_forget]
  question_key: [question, question]
  answer_key: [answer, answer]
  base_answer_key: [answer, paraphrased_answer]
  perturbed_answer_key: [perturbed_answer, perturbed_answer]

  generation:
    max_length: 200
    max_new_tokens: null

  save_generated_text: true

  ds_size: 300

  overwrite: true
  use_pretrained: false

  batch_size: 30